### ISSUE TITLE
Add a defrag/squeeze function.

### ISSUE THREAD

**Issue by IanSeyler** [ReturnInfinity/BMFS#10]

**Comment by tay10r** [comment]
Adding the ability to change the block size of an existing file system should be able to accomplish this. Changing the block size to a single byte would leave no unused space and do a pretty good job at lowering the disk size.

I'm adding this to the to-do list for the next release.

**Comment by dd6905** [comment]
why not use vdo?

**Comment by tay10r** [comment]
What's VDO?
