### ISSUE TITLE
Autotools incorporation

### ISSUE THREAD

**Issue by vilhelmgray** [ReturnInfinity/BMFS#11]
Incorporating the [GNU build system (a.k.a. Autotools)](http://en.wikipedia.org/wiki/GNU_build_system) could greatly improve the portability of this project: users would simply execute the idiomatic `./configure && make && make install` to configure, build, and install the project.

Since this project is coded entirely in standard C, adding Autotools to the project should be a trivial endeavor. I am willing to submit a pull request for the feature, but I first want to know if there are any objections or comments before I begin working.

**Comment by IanSeyler** [comment]
Sounds good to me. It would be great if the bmfs binary was copied to somewhere in the path.
