### ISSUE TITLE
Directory Support

### ISSUE THREAD

**Issue by tay10r** [ReturnInfinity/BMFS#15]
How about adding directory support to BMFS? I noticed that there is a 64 bit integer unused in the entry structure. One of those eight bytes could easily be used as a directory flag, without changing the size of the structure.

**Comment by IanSeyler** [comment]
Yes, there is free space in the structure but we are still limited to 64-files maximum as BMFS only uses on 4KiB block for the file information.

Perhaps this will be extended in BMFS v2 ;)

**Comment by tay10r** [comment]
Ah, hope you'll let me help you work on V2

**Comment by tay10r** [comment]
The current implementation is using a bit in the unused portion of the entry to indicate that the starting block of the entry is pointing to another directory on the hard disk. This method preserves compatibility with the current layout of BMFS.

**Comment by tay10r** [comment]
After two years, finally got around to adding directory support. Releasing v2.0.0 today, which includes this feature. Oh, the nostalgia!
