### ISSUE TITLE
File Permissions

### ISSUE THREAD

**Issue by ghost** [ReturnInfinity/BMFS#31]
File permissions would be useful in helping Alloy determine which files may be executed or not.

They'd also be helpful in making some files (like alloy.bin) read-only, since writing to it could destroy the system.

The permissions would be basic:

 - r : read permission
 - w : write permission
 - x : execute permission

Which is inspired by POSIX file permissions, but simplified.

The permission bits would occupy the currently unused space in the BMFS entries.

**Comment by tay10r** [comment]
Release 8776289 (v2.0.0) contains a `Flags` field in the entry structure for this purpose. There needs to be more support for handling file permissions in the library before this issue can be closed.
