### ISSUE TITLE
Checksum Tool

### ISSUE THREAD

**Issue by ghost** [ReturnInfinity/BMFS#33]
Write a tool that calculates a checksum (like SHA512) of entries or regions within the disk.

The tool would be useful in determining if critical files (like alloy.bin) or regions (pure64 and the kernel) have been damaged.

This is different, and far more useful, than a checksum tool that calculates a hash from the entire disk.

**Comment by tay10r** [comment]
It would be better for regular checksum tools to be used for this purpose, at least when it comes to file integrity. It would be better to add checksum fields for the file system header and allocation table, since they are not visible to these tools.

**Comment by tay10r** [comment]
Newest commit in the develop branch, at 1b29244 contains CRC32 checksums in the allocation table and file system header. There will also be checksums in the directory entries. File data can be checked with other hashing tools, using the disk utility like this:

```bash
bmfs cat /file/to/check | sha256sum
```
Provided that the expected hash is known.
