### ISSUE TITLE
Driver support in User Space/FUSE

### ISSUE THREAD

**Issue by dd6905** [ReturnInfinity/BMFS#45]
Currently BMFS seems to be positioned as an app rather than a file system with a driver. I personally believe that won't do well with the long term look and feel of bmfs in the Unix/POSIX world. Eventually to get a wider audience, BMFS will need to conform to the Unix way of doing things. 
such as
    mkfs -t bmfs /dev/sda
    mkfs.bmfs -o blah /dev/sda
so it becomes one of the supported file systems through the operating system rather than an app that supports it's uniq proprietary file system.

I'm not looking at what Windows would do at all. Who really uses windows to run ExaByte file systems?

Should be able to support integration with FUSE to load the file system drivers into userspace memory. I think Kernel Space will hinder future upgradeability when Kernels change.

**Comment by tay10r** [comment]
We had a FUSE program a while ago, they're pretty easy to write. I don't know if we'll bring it back though. BMFS isn't meant for Unix, because it's not going to support file permissions or ownership IDs. We had a version of BMFS that did all that, and it becomes much harder to use.

**Comment by tay10r** [comment]
> Should be able to support integration with FUSE to load the file system drivers into userspace memory. I think Kernel Space will hinder future upgradeability when Kernels change.

FUSE programs don't go into kernel space, they're in user space.

**Comment by dd6905** [comment]
Correct FUSE is in user space. File Permission or ownership ID is solutely required for a file server. If there are groups of people/work environment. The only way I can see a file system without perms/UIDs is for individual use. I know for few projects, we needed the security enhanced linux attributes to the file system. I never bothered to look into if the file system actually had to be smart about SELinux, or if the linux kernel handled everything. but definitely all the MAC stats, and GUID/UID is required UMASK support world/group/owner access control. I don't know enough about windows file systems internals but unix facing needs some kind of access control support. If you had some fuse code, I'd like to take a look at what you had.

**Comment by dd6905** [comment]
Think there was some misunderstanding somewhere. Yes FUSE is User Space, don't want the Kernel Space. I think interoperability and compatibility  and portability and upgradeability away from the OS/Kernel as much as possible.
