### ISSUE TITLE
SPAN Multiple Disk

### ISSUE THREAD

**Issue by dd6905** [ReturnInfinity/BMFS#48]
A single file should be able to span multiple BMFS disks. A single large file 45TB file which requires spanning multiple disks utilizing novel RAID and when we've exhausted that, Spanning Multi-Server techniques for larger files.

**Comment by tay10r** [comment]
That's what software like LVM is for. If we wanted to support multiple disks on a single file system, that should be handled on a block device level, not a file system one.

**Comment by dd6905** [comment]
Some file systems have these features built in. I assumed this BMFS could be used completely independent of additional layers like LVM. like ZFS that has these more integrated into the architecture. LVM2 kinda sucks in that it meets basic needs, but will requires a lot HUMAN interaction to kind of keep it managed when file systems are growing like crazy. LVM has the features to keep growing it, but not automatically. I feel the Bare Metal concept is more plug and play or at least that it the need from my end. The file system is the choice how to minimize the manhours. The file systems are no longer a install once and forget. With the requirement to resize/grow sizes online, zero downtime. Either users invest more high cost $$$ into and infrastructure that can support that, or switch to a file system that handles more of that. ZFS helps keep it more automated in the file system design. I didn't like ZFS because even tho it can potentially outperform RAID,  it needed to be tuned first which took a lot of initial time, and learning curve. Who wants to spend that kind of time. I ultimately dropped ZFS due to the need to re-tune it when the file server environent changed it significantly. It handled a linear growth path like just adding more disks, but it really didn' handle exponential growth. I'm sure it might have been able to, but I sure didn't want to spend the time to make is so. We are having to spend months to get new large systems up, and retuning ineresting to me to waste that kind of time. Ultimately we are using features from multiple file systems to manage everything. I think the next generation file system is an all in one solution for now. I assumed this BMFS proect was a low level block level file system. with disk layout speced out, tools to both transfer within and between file systems and manage/debug/recover corrupt file systems, and ultimately integrated into the operating system.
