### ISSUE TITLE
Metadata Inegrity Checks

### ISSUE THREAD

**Issue by dd6905** [ReturnInfinity/BMFS#58]
Are there any form of integrity checks that there hasn't been any corruption in the data? or metadata?
I think it can be done easily by supporting varialbe file block sizes.

**Comment by tay10r** [comment]
There use to be. I agree that it should be added again

**Comment by dd6905** [comment]
I evaluated all major file systems at the time, and one of them actually had the problem that data could be lost. I think it was the one by SGI. Data could mysteriously disappear and that was from the choice and design of the file system to prioritize performance. Ultimately it was dropped from our list of usable file systems because data integrity was number one issue in all our primary file systems, but we would allow it in our secondary file servers and mirrors since we had the feature to self heal not only metadata, but corrupt data  itself. with large number of drives, low % of bad sectors, the total number of bad sectors becomes an issue. The per file variable block sizing feature will also require  less code for supporting tools to assist in healing a corrupt file system data
