### ISSUE TITLE
Staggared BMFS integrity checks

### ISSUE THREAD

**Issue by dd6905** [ReturnInfinity/BMFS#59]
Can't have all of them going off at the same time. In a 32 drive server, it bogs down the servers to noticeable levels, so need feature to be able to sequetialize one BMFS system check from another drive in the same server.

**Comment by tay10r** [comment]
Sequencing is out of file system scope.

**Comment by dd6905** [comment]
Is there some automated regular integrity check of file system data, metadata and or journal? If so, is this done at a regular interval automatically, at bootup(to confirm integrity of file system)/mount time/ crash recovery? If only done at mount time or crash recovery, that will add huge delays when needing to enable file system in cold storage. The solution needs to deal with as much of this after bringing the file server online which means the better solution would be to defer as much of file system integrity after boot/mount as possible. Consider it.
