### ISSUE TITLE
the `initialize` function of `bmfs` is undocumented

### ISSUE THREAD

**Issue by xieyuheng** [ReturnInfinity/BMFS#8]
the `initialize` function of `bmfs` is undocumented

`bmfs disk.image initialize 128M path/to/bmfs_mbr.sys path/to/pure64.sys path/to/kernel64.sys` 

`==`                                                                                         

`dd if=/dev/zero of=bmfs.image bs=1M count=128` 
`bmfs bmfs.image format /force` 
`dd if=bmfs_mbr.sys of=bmfs.image bs=512 conv=notrunc` 
`cat pure64.sys kernel64.sys > software.sys` 
`dd if=software.sys of=bmfs.image bs=512 seek=16 conv=notrunc` 

`=/=`                                                                                        

`dd if=/dev/zero of=bmfs.image bs=1M count=128` 
`bmfs bmfs.image format /force` 
`dd if=bmfs_mbr.sys of=bmfs.image bs=512 conv=notrunc` 
`cat pure64.sys kernel64.sys > software.sys` 
`dd if=software.sys of=bmfs.image bs=512 seek=1 conv=notrunc` 

`==`                                                                                      

`dd if=/dev/zero of=bmfs.image bs=1M count=128` 
`bmfs bmfs.image format /force` 
`cat bmfs_mbr.sys pure64.sys kernel64.sys > software.sys` 
`dd if=software.sys of=bmfs.image bs=512 conv=notrunc`

**Comment by tay10r** [comment]
@xieyuheng The first set of commands look right to me. Is there anything you need documented? The command is for initializing a disk image with the boot files and kernel. It's not currently a general purpose tool, it's just something we use for the build scripts.
